# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Exred
email: exredorg@gmail.com
description: >- 
    Flow-based programming environment written in Elixir
    Run it as an Erlang release or in a docker container.
    Docker image is also availbale for Raspberry Pi.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://exred.org"
twitter_username: ""
github_username:  exredorg

# Build settings
markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"
#remote_theme: "poole/hyde"

include:
    - "_pages"

plugins:
    - jekyll-feed


defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      classes: wide
      sidebar:
        nav: guide_docs
      author_profile: false
      read_time: true
      comments: false
      share: false
      related: false
  - scope:
      path: "assets/downloads"
    values:
      download: true


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
